version: 0.2

phases:
  pre_build:
    commands:
      - echo Stating...
      - yum install -y docker
      - service docker start
      - docker info
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      #- docker build -t $IMAGE_REPO_NAME:latest .
      #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      #- docker push $REPOSITORY_URI:latest
      #- docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"$TASK_DEFINITION_NAME","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > EcsImageFilename.json
artifacts:
    files: EcsImageFilename.json